// ==UserScript==
// @name        [Novel]Downloader
// @description novelDownloaderHelper, press key "shift+d" to show up.
// @version     1.45.18.${now}
// @Date        ${nowStr}
// @author      dodying
// @namespace   https://github.com/dodying/UserJs
// @supportURL  https://github.com/dodying/UserJs/issues
// @icon        https://raw.githubusercontent.com/dodying/UserJs/master/Logo.png
// @require     https://cdn.bootcss.com/jquery/2.1.4/jquery.min.js
// @require     https://cdn.bootcss.com/jszip/3.0.0/jszip.min.js
// @require     https://cdn.bootcss.com/FileSaver.js/1.3.8/FileSaver.min.js
// @require     https://greasyfork.org/scripts/21541-chs2cht/code/chs2cht.js?version=605976
// @require     https://greasyfork.org/scripts/32483-base64/code/base64.js?version=213081
// @grant       GM_xmlhttpRequest
// @grant       unsafeWindow
// @grant       GM_setValue
// @grant       GM_getValue
// @grant       GM_listValues
// @grant       GM_deleteValue
// @grant       GM_setClipboard
// @grant       GM_registerMenuCommand
// @connect     *
// @run-at      document-end
//              文学
// @include     http://gj.zdic.net/archive.php?aid=*
// @include     http://www.99lib.net/book/*.htm
// @include     http*://www.kanunu8.com/book*
// @include     http://www.my285.com/*/*
// @include     http*://wx.ty2016.net/*/*
// @include     http*://www.ty2016.net/*/*
// @include     http://scp-wiki-cn.wikidot.com/*
// @include     http://www.scp-wiki.net/*
//              正版
// @include     http*://book.qidian.com/info/*
// @include     http*://read.qidian.com/chapter/*
// @include     http*://vipreader.qidian.com/chapter/*
// @include     http*://www.hongxiu.com/book/*
// @include     http*://www.hongxiu.com/chapter/*
// @include     http*://www.readnovel.com/book/*
// @include     http*://www.readnovel.com/chapter/*
// @include     http*://www.xs8.cn/book/*
// @include     http*://www.xs8.cn/chapter/*
// @include     http://chuangshi.qq.com/bk/*/*-*.html
// @include     http://yunqi.qq.com/bk/*/*-*.html
// @include     http://dushu.qq.com/intro.html*
// @include     http://book.qq.com/intro.html*
// @include     http://book.tianya.cn/html2/dir.aspx?bookid=*
// @include     http://book.tianya.cn/chapter-*
// @include     http*://www.ciweimao.com/book/*
// @include     http*://www.ciweimao.com/chapter-list/*/book_detail
// @include     http*://www.ciweimao.com/chapter/book_chapter_detail*
// @include     http://www.3gsc.com.cn/bookreader/*
// @include     http://www.3gsc.com.cn/bookcon/*
// @include     http://book.zongheng.com/showchapter/*
// @include     http://book.zongheng.com/chapter/*
// @include     http://huayu.baidu.com/showchapter/*
// @include     http://huayu.baidu.com/chapter/*
// @include     http://www.17k.com/list/*
// @include     http://www.17k.com/chapter/*
// @include     http://www.8kana.com/book/*
// @include     http://www.8kana.com/read/*
// @include     http://www.heiyan.com/book/*
// @include     http://b.faloo.com/f/*
// @include     http://b.faloo.com/p/*
// @include     http://www.jjwxc.net/onebook.php*
// @include     http://www.xxsy.net/books/*
// @include     http://www.xxsy.net/chapter/*
// @include     http://book.zhulang.com/*/*
// @include     http://book.hjsm.tom.com/*/c*.html
// @include     http*://www.kanshu.com/files/article/html/*
// @include     http://vip.book.sina.com.cn/weibobook/book/*
// @include     http://vip.book.sina.com.cn/book/play/*-*.html
// @include     http://www.lcread.com/bookpage/*
// @include     http://www.motie.com/book/*
// @include     http://www.shuhai.com/read/*
// @include     http://www.xiang5.com/booklist/*
// @include     http://www.xiang5.com/content/*
// @include     http://read.fmx.cn/files/article/html/*
// @include     http://novel.feiku.com/*/*
// @include     http*://www.kujiang.com/book/*
// @include     http://www.tadu.com/book/*
// @include     http*://yuedu.163.com/newBookReader.do*
// @include     http*://yuedu.163.com/source/*
// @include     http*://yuedu.163.com/book_reader/*
// @include     http*://guofeng.yuedu.163.com/newBookReader.do*
// @include     http*://guofeng.yuedu.163.com/source/*
// @include     http*://guofeng.yuedu.163.com/book_reader/*
// @include     http*://caiwei.yuedu.163.com/newBookReader.do*
// @include     http*://caiwei.yuedu.163.com/source/*
// @include     http*://caiwei.yuedu.163.com/book_reader/*
// @include     http*://ebook.longmabook.com/showbook*
// @include     http*://ebook.longmabook.com/showpaperword*
// @include     http://www.yueloo.com/read/*
// @include     http://www.ycsd.cn/html/*
// @include     http://book.xxs8.com/*/*
// @include     http://www.longruo.com/chapterlist/*
// @include     http://www.longruo.com/catalog/*_*.html
// @include     http://www.cjzww.com/book/*
// @include     http://www.cjzww.com/chapter/*.html
// @include     http://www.hxtk.com/books/getBookAllChapters.action*
// @include     http://www.hxtk.com/books/readBook.action*
// @include     http*://www.hongshu.com/bookreader/*
// @include     http*://www.hongshu.com/content/*
// @include     http://www.qwsy.com/mulu/*
// @include     http://www.qwsy.com/read.aspx*
// @include     http://www.rongshuxia.com/book/volume/*
// @include     http://www.rongshuxia.com/chapter/*
// @include     http://vip.shulink.com/files/article/html/*
// @include     http://www.4yt.net/directory/*
// @include     http://www.4yt.net/read/free/*
// @include     http://www.soudu.net/html/*
// @include     http://www.fbook.net/book/*
// @include     http://book.tiexue.net/Book*/*
// @include     http://www.wjsw.com/html/*
// @include     http://www.yokong.com/book/*.html
// @include     http://www.chuangbie.com/book/catalog*
// @include     http://www.chuangbie.com/book/read*
// @include     http://www.msxf.net/book/*.html
// @include     http://mm.msxf.net/book/*.html
// @include     http*://www.popo.tw/books/*/articles*
// @include     http://www.anyew.cn/chapters/*
// @include     http://www.anyew.cn/book/*.html
// @include     http*://yuedu.baidu.com/ebook/*
//              轻小说
// @include     http://www.wenku8.com/novel/*
// @include     http*://book.sfacg.com/Novel/*
// @include     http://xs.dmzj.com/*.shtml
// @include     http://www.yidm.com/article/info/*.html
// @include     http://www.yidm.com/article/html/*.html
// @include     http://book.suixw.com/modules/article/reader.php*
// @include     http*://www.iqing.com/book/*
// @include     http*://www.iqing.com/read/*
//              盗贴
// @include     http://www.chuanyue8.net/files/article/html/*
// @include     http://www.22ff.com/xs/*
// @include     http://www.xntk.net/html/*
// @include     http://www.xntk.net/book_j.php*
// @include     http://www.kong.so/*/*
// @include     http://www.hunhun520.com/book/*
// @include     http://www.xiaoshuokan.com/haokan/*
// @include     http://www.3zcn.org/3z/*
// @include     http://www.ggdown.com/*
// @include     http*://www.daizitouxiang.com/du/*
// @include     http://www.blwen.com/*.html
// @include     http://www.mpzw.com/html/*
// @include     http://www.00xs.cc/xiaoshuo/*/*/
// @include     http://www.kenshu.cc/xiaoshuo/*
// @include     http://www.pbtxt.com/*/*
// @include     http://www.8shuw.net/book/*
// @include     http*://www.hjwzw.com/Book/Chapter/*
// @include     http*://www.hjwzw.com/Book/Read/*
// @include     http://www.5858xs.com/*.html
// @include     http://www.teteam.com/xiaoshuo*.shtml
// @include     http://www.teteam.com/modules/article/reader.php*
// @include     http://www.23txt.com/files/article/html/*
// @include     http://www.59zww.com/files/article/xiaoshuo/*
// @include     http://www.bookba.net/mulu-*-list.html
// @include     http://www.bookba.net/read-*-chapter-*.html
// @include     http://www.wenxuemm.com/book/*
// @include     http://www.630book.cc/shu/*
// @include     http://www.zhuaji.org/read/*
// @include     http://www.shunong.com/*/*
// @include     http://www.hkxs99.net/*/*
// @include     http://www.doulaidu.com/xs/*
// @include     http://www.shuotxts.net/*.html
// @include     http://www.fkzww.com/Html/Book/*
// @include     http://www.bookgew.com/Html/Book/*
// @include     http://www.shumil.com/*/*
// @include     http://www.520xs.la/*/*
// @include     http://www.2kxs.com/xiaoshuo/*
// @include     http://www.mianhuatang.la/*/*
// @include     http://www.baoliny.com/*.html
// @include     http://www.dajiadu.net/files/article/html/*/*
// @include     http://www.paoshuba.cc/Partlist/*
// @include     http://www.qmshu.com/html/*
// @include     http://www.xfqxsw.com/book/*
// @include     http://www.zwda.com/*/*
// @include     http*://www.sto.cc/*
// @include     http://www.musemailsvr.com/*.shtml
// @include     http://www.50zw.co/book_*/*
// @include     http://www.piaotian.com/html/*
// @include     http://www.23xs.org/shu/*
// @include     http://www.cuisiliu.com/book/*
// @include     http://yi-see.com/art_*.html
//              18X
// @include     http://www.lewenxs.net/read/*.html
// @include     http://www.wodexiaoshuo.cc/*/*
// @include     http://www.shubao26.com/book/*.html
// @include     http://www.shubao26.com/read/*.html
// @include     http://www.lawen520.com/txtbook/*.html
// @include     http://www.lawen520.com/quanwen/*.html
// @include     http://bbs.6park.com/bbs4/messages/*.html
// @include     http://bbs.6park.com/bbs4/gmessages/*.html
// @include     http://web.6park.com/classbk/md*.shtml
// @include     http://web.6park.com/classbk/messages/*.html
// @include     http://www.neixiong888.com/xiaoshuo/*
// @include     http*://www.xncwxw.com/files/article/html/*.html
// @include     http://www.50655.net/*/*
// @include     http://www.bmshu.com/book*
// @include     http://www.beijingaishu.net/files/article/html/*
// @include     http://www.dz8.la/book/*
// @include     http://www.dz8.la/views/*
// @include     http://www.kewaishu.info/yuedu/*
// @include     http://www.lmzww.net/jlgcyy/*
// @include     http://www.zxxs259.com/read/*
// @include     http://www.zixuanxs.com/*
// @include     http://www.ncwx.hk/wx/*
// @include     http://x520xs.com/*/*
// @include     http://www.7zxs.com/ik258/*
// @include     http://www.ik777.net/ik258/*
// @include     http://www.jipinzw.com/*/*
// @include     http://www.qindouxs.org/files/article/html/*.html
// @include     http://www.5qudu.com/files/article/html/*
// @include     http://www.8xxsw.com/xiaoshuo.asp?id=*
// @include     http://www.8xxsw.com/page.asp?id=*
// @include     http://www.6mxs.com/novel.asp?id=*
// @include     http://www.6mxs.com/pages.asp?id=*
// @include     http://www.3mxs.com/novel.asp?id=*
// @include     http://www.3mxs.com/pages.asp?id=*
// @include     http://www.bsl8.la/read/*
// @include     http://www.fafaxs.cc/read/*
// @include     http://www.shushuwu.cc/novel/*
// @include     http://www.cuiweijuxin.com/files/article/html/*/*.html
// @include     http://www.shubao4.com/read/*.html
// @include     http://www.cuiweiju88.com/files/article/html/*.html
// @include     http://www.xitxt.net/book/*.html
// @include     http://www.xitxt.net/read/*.html
// @include     http://www.shenshuw.com/s*/*
// @include     http://www.baqishuku9.com/book/*.html
// @include     http://www.baqishuku9.com/book_read/*.html
// @include     http://www.heihei66.com/*/*
// @include     http://www.quanshuwu.com/book/*.aspx
// @include     http://www.quanshuwu.com/article/*.aspx
// @include     http://www.dzxs.cc/read/*.html
// @include     http://www.mlxiaoshuo.com/book/*.html
// @include     http://www.mlxiaoshuo.com/chapter/*.html
// @include     http://www.haianxian.net/book/*/*
// @include     http://www.xiaoqiangxs.com/*
// @include     http://18av.mm-cg.com/novel*
// @include     http://18av.mm-cg.com/serch*
// ==/UserScript==
